'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pathology.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _12137617_scientific_background_collage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12137617-scientific-background-collage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _34122532_Sign_up_concept_on_blue_background_with_world_map_and_social_icons__Stock_Photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("34122532-Sign-up-concept-on-blue-background-with-world-map-and-social-icons--Stoc"& _ 
                        "k-Photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _51445246_Sign_up_hand_pressing_button_on_interface_with_blue_background__Stock_Photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("51445246-Sign-up-hand-pressing-button-on-interface-with-blue-background--Stock-Ph"& _ 
                        "oto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _65267631_medical_blood_tube_test_tube_for_laboratory_empty_on_rack_on_a_while_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("65267631-medical-blood-tube-test-tube-for-laboratory-empty-on-rack-on-a-while-bac"& _ 
                        "kground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _65267631_medical_blood_tube_test_tube_for_laboratory_empty_on_rack_on_a_while_background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("65267631-medical-blood-tube-test-tube-for-laboratory-empty-on-rack-on-a-while-bac"& _ 
                        "kground1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back_and_forth_questions_md_wm_v2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_and_forth_questions_md_wm_v2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner_pms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_pms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner_pms1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_pms1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner_pms2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner_pms2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banner61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banner61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Biochemist1Trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Biochemist1Trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Biochemist1Trans1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Biochemist1Trans1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changepasswords() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changepasswords", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changepasswords1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changepasswords1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changepasswords2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changepasswords2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property color_background_surface_solid_18481_640x1136() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("color_background_surface_solid_18481_640x1136", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forgot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forgot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property forgotpassword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forgotpassword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property galaxy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galaxy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property galaxy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galaxy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property maxresdefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxresdefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MdiImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MdiImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property testing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("testing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
